//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStore_3B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook
    {
        public int Book_ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Is_Available { get; set; }
        public int User_ID { get; set; }
    }
}
