//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookStore_3B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int User_ID { get; set; }
        public string Username { get; set; }
        public string Email_add { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string Cell_Num { get; set; }
        public string Street { get; set; }
        public string House_No { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public byte[] Photo { get; set; }
    }
}
